set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"

set-option -g status-justify "left"
set-option -g history-limit 64096

set-option -g status-position bottom
set-option -g status-fg black
set-option -g status-bg black
set -g pane-active-border-style fg=#c5c7c5,bg=default
# set -g pane-active-border-style fg=#e8e8e8,bg=#e8e8e8
# set -g window-style fg=colour238,bg=default
set -g window-style fg=#8e868b,bg=default
set -g window-active-style fg=#c5c7c5,bg=default

# Vim mode window movement.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

