set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"

set-option -g status-justify "left"
set-option -g history-limit 64096

set-option -g status-position bottom
set-option -g status-fg black
set-option -g status-bg black
set -g pane-active-border-style fg=#c5c7c5,bg=default

# Light mode.
# set -g window-style fg=#c5c7c5,bg=default
# set -g window-active-style fg=#333333,bg=default

# Dark mode.
set -g window-style fg=#8e868b,bg=default
set -g window-active-style fg=#e8dcb7,bg=default

# Vim mode window movement.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Start with fish by default.
set-option -g default-shell /opt/homebrew/bin/fish
set -g default-command /opt/homebrew/bin/fish
